#! /bin/bash
if [ "$1" -ot xmonad.hs ]; then
  echo "$1 outdated; rebuilding with stack."
  exec stack ghc -- --make xmonad.hs -i -ilib -lxklavier -fforce-recomp -main-is main -v0 -o "$1"
else
  echo "$1 up to date; not rebuilding."
fi
